### ISSUE TITLE
How do I do the opposite?

### ISSUE THREAD

**Issue by tehfailsafe** [eface2face/meteor-client#1]
Hello,

This is a great idea! But I am currently stuck on the inverse problem, how to add a library that is built for gulp / browserify workflow into the meteor packaging system. 

Specifically, I am looking at https://github.com/callemall/material-ui.  I have an issue open there but the creators don't use meteor, so aren't sure how to help.

Any advice on wrapping it up into a format that meteor can consume?

**Comment by murillo128** [comment]
Sorry, can't help on that, check on Meteor forums instead.
